[options]
db_host = db
db_port = 5432
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
data_dir = /var/lib/odoo
http_port = 8069
http_interface = 0.0.0.0
list_db = True
max_cron_threads = 0
proxy_mode = False
without_demo = True
workers = 0
